---
- name: installing nginx
  hosts:
    - _web_server
  vars:
    ansible_ssh_private_key_file: "/home/ec2-user/NVPEM.pem"
  tasks:
    - name: installing docker
      shell: "sudo yum install docker -y; sudo systemctl start docker"
    - name: installing nginx
      shell: "sudo docker pull nginx; sudo docker run -d -p 80:80 nginx"

